# -*- coding: utf-8 -*-
"""Practica 3 RGyGJ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h0Vd8TCh6VsrVe5eMFeD1Neff0w2PcZS
"""

#PRACTICA #3
#Pedimos al usuario la velocidad y distantcia de ventaja que tiene la tortuga

velocidad_tortuga = float(input("Ingrese la velocidad de la tortuga: "))
distancia_tortuga = float(input("Ingrese la distancia recorrida por la tortuga: "))

if velocidad_tortuga == str and distancia_tortuga == str:
    raise TypeError ("No ingresó datos numericos.")

else:
#Calculo el tiempo

    segundos = distancia_tortuga // velocidad_tortuga

#Calculo las horas, minutos y segundos de ventaja para la tortuga. El simbolo "//" es la division entera de dos numeros
    horas_tor = segundos // 3600
    segundos_restantes = segundos % 3600
    minutos = segundos_restantes // 60
    segundos_tor = segundos_restantes % 60

    print("Aquiles le dio de ventaja a la tortuga de: ", horas_tor, "horas", minutos, "minutos y ", segundos_tor, "segundos.")

#Ahora sabemos que Aquiles es 10 veces mas rapido que la tortuga 
    print("")
    print("ahora aquiles comienza la carrera y es 10 veces mas rápido que la tortuga")

    velocidad_aquiles = 10 * velocidad_tortuga
    tiempo_encuentro = 0
    distancia_aquiles = velocidad_aquiles * tiempo_encuentro

# ademas sabemos que la tortuga sigue caminando 
    distancia_tortuga_2 = distancia_tortuga + (tiempo_encuentro * velocidad_tortuga) 

# establecemos un contador de tiempo para calcular la distancia  en la que se encuentran
print("¿Donde se encontraran?")

while distancia_aquiles < distancia_tortuga_2:
        tiempo_encuentro += 1
        distancia_aquiles = velocidad_aquiles * tiempo_encuentro
        distancia_tortuga_2 = distancia_tortuga + (tiempo_encuentro * velocidad_tortuga) 
        
        print("la tortuga recorrió" , distancia_tortuga_2, "metros luego de ", tiempo_encuentro, "segundos.")    
        print("Aquiles recorrió" , distancia_aquiles, "metros luego de ", tiempo_encuentro, "segundos.")
        
        print("")
    
        if  distancia_aquiles >= distancia_tortuga_2:
            tiempo_encuentro = float(tiempo_encuentro) 
 #considero el tiempo de ventaja y transformo a horas, minutos y segundos
            tiempo_total = segundos + tiempo_encuentro
        
            hora_total = tiempo_total // 3600
            restante = tiempo_total % 3600
            minutos_total =  restante // 60
            segundos_total = restante % 60
        
            print("Aquiles alcanza a la tortuga luego de ", hora_total, "horas", minutos_total, "minutos y ", segundos_total, "segundos.")
            break